### ISSUE TITLE
Ninja stars documentation for new commits added to PR

### ISSUE THREAD

**Issue by jaymcnallie** [reviewninja/review.ninja#1026]
We've had several reviews opened against our project where a user will review the code and star the PR and several days later come back to find that all stars have been removed from the review.  We have not been able to determine a pattern or certain set of steps that always results in the stars disappearing.  It does not happen to all of our reviews but has happened repeatedly.

**Comment by dfarr** [comment]
We associate ninja stars with the **current head commit** of the PR. When new commits are added to a PR, all stars are "cleared". (They actually still technically exist, they just exist on a commit which is now out of date.) 

We do this because a new commit can fundamentally change the nature of the code you review, thus necessitating a new review. We are exploring ways to surface previous commits in RN (#974), this would include the stars on old commits.

**Comment by wmcnalli** [comment]
Makes sense and probably explains our issue.  May I suggest adding a note to the ninja stars documentation page reflecting this behavior.  I looked there before I opened this issue... promise.  ;)

**Comment by dfarr** [comment]
Added to [documentation](https://docs.review.ninja/stars/)!
