### ISSUE TITLE
 Allow ReviewNinja to comment in in GitHub doesn't work?

### ISSUE THREAD

**Issue by warden** [reviewninja/review.ninja#1036]
I don't want ReviewNinja to post comments and review statuses in comments to GitHub. I was expecting that if I uncheck the " Allow ReviewNinja to comment in in GitHub" then it will only base on the reviewninja's comment database for review management, but it still writes comments to GH.
So, what does this option really mean?

**Comment by dfarr** [comment]
This option disables our [review-ninja github user](https://github.com/review-ninja) from posting the [ninja with a speech bubble comment](https://github.com/reviewninja/review.ninja/pull/1034#issuecomment-171846114) on a PR. 

ReviewNinja has no comment database, all comments live in GitHub itself, this is highly advantageous because (a) all contributions via RN are automatically visible in GH, and (b) users can decide to contribute to code review without leaving GH if they choose. It is also possible to note that when users create comments on lines of code in RN, they are making those comments in the context of their own user (and not a RN context), exactly as they would if they commented in GH.

**Comment by warden** [comment]
Got it, then I will need to wait for #1033... thanks!
