### ISSUE TITLE
Web hooks

### ISSUE THREAD

**Issue by amlwwalker** [reviewninja/review.ninja#1058]
Are there reviewninja web hooks?
Can I tell reviewninja to tell an end point when a ninja star has been awarded?

**Comment by dfarr** [comment]
ReviewNinja does not offer this.

However, instead of having an additional webhook in ReviewNinja, I would suggest using [GH's status webhook](https://developer.github.com/v3/activity/events/types/#statusevent). This will be fired any time any status changes, but you can check the context for "code-review/reviewninja" to isolate ReviewNinja statuses. 

You could deduce ninja star information from the message, however (depending on your use case), it may be easier to check the status and do thing based on this.
