### ISSUE TITLE
Heroku template has incorrect mongodb settings

### ISSUE THREAD

**Issue by killthrush** [reviewninja/review.ninja#1069]
After deploying the default ReviewNinja template to Heroku, I would get errors like 'Cannot GET /" when trying to launch the app.  

The logs would show this error during bootstrapping:
`{ [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONNREFUSED' }`

I traced the problem to a bad environment var in the template.  **MONGODB_URI** appears in the config, while **MONGODB** appears in the code.  After copying the config setting and bootstrapping again, the app worked fine.  I'd submit a pull request but I'm not terribly familiar with Node or Heroku and am not sure where to make the change.

**Comment by thojansen** [comment]
This should be here and the reason is that heroku has change the name of that environment variable (likely choosing a generic name because they are now called mLab instead of mongolab). It was MONGOLAB_URI before.
https://github.com/reviewninja/review.ninja/blob/6ffce9f7d153b3e164c96cbd07d0c99e41df248a/src/config.js#L99
https://github.com/reviewninja/review.ninja/blob/6ffce9f7d153b3e164c96cbd07d0c99e41df248a/src/config.js#L87

That should also be the issue for #1072. Do you want to create a PR for that?

**Comment by killthrush** [comment]
Sure, I'll take care of this and do some testing.
