### ISSUE TITLE
Allow !star to be sticky

### ISSUE THREAD

**Issue by alecf** [reviewninja/review.ninja#1079]
As a part of our review flow, we often add a bunch of !fix comments, but still include a !star - basically as a way of saying "if you fix the other issues, you get the !star, and I trust you enough to fix those issues" 

But as it stands today, as soon as you push new code, the ninja star goes away. It would be nice to have a "sticky star" which survives pushes. this could just be a flag per-project (so that all stars are "sticky") or you could introduce a new flag (!stickystar ? !superstar ?) which indicates that the reviewer trusts the author enough to fix issues & merge themselves.

**Comment by dfarr** [comment]
Thanks for the suggestion @alecf. We believe that a new commit necessitates a new review, because the code *may* have fundamentally changed. 

I see two potential feature requests:

1) A "superstar" that survives new commits on a PR

2) A setting on the repo to allow normal stars to survive new commits


I will leave this issue open as a place to discuss your proposal. We are also always looking for PR contributions!

**Comment by dfarr** [comment]
As ReviewNinja is no longer in active development mode (see #1132), I will close this issue.
