### ISSUE TITLE
Staged access request

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#380]
As per Twitter suggestion, we should consider staging the repository access requests
https://twitter.com/RobertReiz/status/515564165990473728 - ask for only public, and then have an extra step for private repos.

**Comment by withkiki** [comment]
@rwreynard , based on 3 feedbacks, 
 
2 votes  
![screen shot 2015-02-06 at 3 08 27 pm](https://cloud.githubusercontent.com/assets/7938229/6089073/2232401a-ae12-11e4-91fa-04cd7c18b500.png)
reason: +2, right next to the repo, easy to understand.
             -1, don't like reading, and hyperlink not cool, suggested to combine with lock icon.
                 (but lock icon without label or explanation somehow confusing).

1 votes
![screen shot 2015-02-06 at 3 08 40 pm](https://cloud.githubusercontent.com/assets/7938229/6089125/e4a3fcd8-ae12-11e4-81ab-993938391145.png.
 reason: +1, fast to scan, clear to know the current model.
              -2, far from repo search bar, overlooked. 
                   The radio button will redirecting to another page seems             
                   surprised.

**Comment by dfarr** [comment]
I like the first one :+1:

**Comment by withkiki** [comment]
Yes, we can go for the first one. The wording might need to be reviewed, which is not my strength. Some help? @dfarr @rwreynard. :cake: :fork_and_knife:

**Comment by dfarr** [comment]
It's perfect!

**Comment by rwreynard** [comment]
"Showing" is a bit misleading only because initially you're not showing anything. Until you search and open a list nothing is "showing". 

Perhaps: "You've enabled access to your public repositories. Enable private repositories."
and, "You've enabled access to your public and private repositories. Disable private repositories."

The link will have the standard ReviewNinja link style? Actually now I see we're inconsistent, always standard green but sometimes underline on hover, sometimes just dark green on hover. I vote for underline - simple.

**Comment by benboeser** [comment]
Done
