### ISSUE TITLE
Change "signout" botton

### ISSUE THREAD

**Issue by withkiki** [reviewninja/review.ninja#540]
New button: http://fortawesome.github.io/Font-Awesome/icon/power-off/.

**Comment by fabianschwarzfritz** [comment]
After discussion with @rwreynard : As github's icon logs the user out from Github, we do not want to use the same icon as Githhub does. We decided to use http://fortawesome.github.io/Font-Awesome/icon/sign-out/ as an alternative. 

Furthermore the user was confused as because the username was clickable as well and the user expected to navigate to a 'review-ninja-user-page' instead signing out from reviewNinja. Therefore the username right of the signout icon should not be clickable at all.
