### ISSUE TITLE
Disable or remove buttons when user does not have permissions

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#560]
- [x] merge PR (need push access)
- [x] create issue (need push access)
- [x] set star (need pull access)

**Comment by fabianschwarzfritz** [comment]
There is another one:
- [ ] delete branch (needs access to branch)

@rwreynard I've a question regarding our ui-guidelines: Is it a better idea idea to _remove_ a button or to _disable_ it and provide a proper tooltip?

**Comment by fabianschwarzfritz** [comment]
merged.

**Comment by dfarr** [comment]
Do we need to say ['No permissions...?'](https://github.com/reviewninja/review.ninja/blob/master/src/client/directives/templates/merge.html#L38) Or could we just leave this blank?

**Comment by fabianschwarzfritz** [comment]
I discussed with @rwreynard and we are going to leave the functionality out with no information if it's not available. This means it's _not visible_ and no information text is needed.
 
The mergebutton will be visible all the time tough, and has an information if it's not mergeable already ('... pull request can't be merged'(. Therefore I decided to just add a permission information in this case so that it's clear why it is _disabled_.

**Comment by dfarr** [comment]
What's the reason for still displaying the button?

**Comment by fabianschwarzfritz** [comment]
I see your point. With no text and no button it looks like this: 
![screen shot 2015-01-27 at 1 12 05 pm](https://cloud.githubusercontent.com/assets/1759672/5927275/35eacb5c-a626-11e4-9786-940caf7023df.png)

The whole merge button area is a bit empty if we hide the button, isn't it? The status is then also only visible by the color of the border. @rwreynard @dfarr ideas?

**Comment by dfarr** [comment]
:+1: I like this approach! ReviewNinja is aimed at developers, they should know when the can/cannot merge

**Comment by fabianschwarzfritz** [comment]
(y)
