### ISSUE TITLE
Expose github path prefix as env variable

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#572]
https://github.com/reviewninja/review.ninja/blob/master/src/server/services/github.js#L15

See issue #409

**Comment by fabianschwarzfritz** [comment]
@dfarr Can you please explain this a little further? I'd be very happy about that because I don't get what the issue is about so far. 

What I got so far: Currently it's already possible to configure the host via server.github.enterprise and the according env variable GITHUB_API_HOST. So what is missing here?

**Comment by fabianschwarzfritz** [comment]
Fixed with  #637

**Comment by dfarr** [comment]
:+1:
