### ISSUE TITLE
Opt-out of PR comments

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#647]
Now that we are introducing repo-wide settings, we could have a setting to disable automatic PR comments. This would resolve #469

**Comment by benboeser** [comment]
big :+1:

**Comment by fabianschwarzfritz** [comment]
@dfarr: question:
With #578 it is now possible to change the repo wide setting for the pull request comments. The comment will only be done because of https://github.com/reviewninja/review.ninja/blob/master/src/server/services/pullRequest.js#L16 , right? So this issue is done or is there something else to do?

**Comment by dfarr** [comment]
Have we verified this is working?

**Comment by dfarr** [comment]
Looks like it is to me :+1:
