### ISSUE TITLE
Surface number of conversation comments

### ISSUE THREAD

**Issue by benboeser** [reviewninja/review.ninja#657]
One interviewee would like to see the number of comments (pull request conversation comments) per pull request to make it easier to identify which ones have conversations without having to go into the detail each time.

**Comment by fabianschwarzfritz** [comment]
The technical implementation of this is done. I also added a first approach for the ui in 008c5799c68cb470ed35c7413aaf311218416f4e on feature/surface-comments. @rwreynard  Please let's  discuss how the number of comments will be displayed in the repository view.

**Comment by fabianschwarzfritz** [comment]
@rwreynard concerning the color: The style technology (sass) we are using to generate css enables to automatically "lighten" and "darken" the colors. 
Instead of... 
```.text-primary.muted {
  color: $brand-primary-muted;
}```
...we can use ...
```.text-primary.muted {
  color: lighten($brand-primary, 20%);
}```

With this we can simply apply the lighten function to the ``text-warning`` for example, and it makes thinks way easier for us. How much percent 'lighter' is the ``$brand-primary-muted`` in comparison to ``$brand-primary``?

**Comment by dfarr** [comment]
:+1: 

```sass
$brand-primary: #3e9a94;
$brand-primary-muted: #addada;
```

**Comment by fabianschwarzfritz** [comment]
We cut to release 1.2 today. This is left over from there. Let's do this asap, this is the next feature I'd like to see on production.

**Comment by fabianschwarzfritz** [comment]
We now display the open and closed issues in on column, as before.

**Comment by rwreynard** [comment]
@fabianschwarzfritz I think this is maybe getting a little overwhelming, I prefer just having one column for issues. What does the muted color mean here? Originally it was simply for closed issues. Also there's a lighter gray for the "0" issues or "0" ninja stars. Here's the original png in case it's helpful.

Can we have tooltips for all of these? "x open issues" "x conversation comments" etc. and for names "dfarr starred" or "dfarr, fabianschwarzfritz, rwreynard starred" - use commas instead of "and" 
When the list gets too long "dfarr, fabianschwarzfritz, rwreynard and 19 others starred"

![reviewninjapullrequestlist](https://cloud.githubusercontent.com/assets/4131576/5986092/cf48a16a-a8a2-11e4-8b45-e97e7ce497e0.png)

**Comment by fabianschwarzfritz** [comment]
@rwreynard we now have one column for the issues. Indeed, the color was originally only for closed issues. Now we are displaying more information though, so currently mute has the following meaning: 
 - comments: Muted if no comments.
 - issues: No mute for open issues. If no open issues, we show the closed issues. Mute the closed issues icon if we have no closed issues.
 - stars: Muted if no stars.
We could keep with this logic, or also completely remove 

Lastly, yes we can change the color of the mute. If we change the 'mute' color for the green, this would also influence other pages in ReviewNinja...

Do we want to stick with the green color for the comment icon or should we use a different color there?

**Comment by fabianschwarzfritz** [comment]
Added tooltips with #711

**Comment by rwreynard** [comment]
@fabianschwarzfritz I'm ok with using the light green instead of the light gray to indicate the "0's" but we should then stop using it for navigation also. So, can you change the "Author" dropdown filter to be the standard mid-green? I think that was the original idea anyway. Same with the tab navigation: mid-green for unselected, dark green for hover + selected. Does that work?

Also, instead of using the closed issue icon for the issue "0" state, use the standard open issue icon.

**Comment by fabianschwarzfritz** [comment]
@rwreynard Hi I see we have now three color: $brand-primary, $brand-primary-muted and $brand-primary-hovered. 
We originally we only had two colors there, now we have three. Changing the tab color is a bit of headache for development, as the tab bar is using the brand-primary and brand-primary muted. Is there another solution? We can also just sit together when you're back. 
I'll change the icon, that's no problem at all.

**Comment by benboeser** [comment]
Tab color still pending
