### ISSUE TITLE
See all "pending" PR across all repos

### ISSUE THREAD

**Issue by dfarr** [reviewninja/review.ninja#683]

**Comment by rwreynard** [comment]
Some users would like to only see the pull requests they're meant to review, with an option to view all

**Comment by casche** [comment]
@dfarr  Are we talking about adding a filter for the Status of the head commit on a pull request?

**Comment by dfarr** [comment]
@casche this would be a list of (probably open) PRs regardless of originating repo. I think the best way to think of it would be a "notifications" area.

**Comment by casche** [comment]
hmm, anyone mind if I work on this? Are there any proposals on where we can place this from @rwreynard or @withkiki ?

It's *somewhat* related to #792, maybe?

**Comment by rwreynard** [comment]
@casche at the moment our solution of branch filtering does not appear to be well understood or used, but there's definitely a need to more effectively highlight the pull requests a specific collaborator needs to be reviewing right now. 

One idea for how this might be implemented is on the pull request list view separate the list into two sections. Ist section "Pending review" which means pull requests that this specific user is meant to be reviewing. 2nd section "All pull requests" which is basically what we have now. That's just one idea. It becomes a de facto task list. We also need to make it easier to configure which pull requests should be reviewed by a specific user.

**Comment by casche** [comment]
Ok. I'm left wondering how how we are to differentiate between what a "Pending PR" (PPR) versus "All-PR" (PR). We could say that if you have ninja-starred a PPR then it is no longer a PPR. It doesn't sound like just viewing the PPR would be enough to consider it reviewed. It is possible that you did not finish your review and I guess the only real indicator that a user has finished a review is a ninja star. 

Does anyone have any other ideas?

**Comment by casche** [comment]
Separating the list into two in a linear layout is going to cause some issues with the infinite scroll. 

_For example:_

![screen shot 2015-03-05 at 1 35 49 pm](https://cloud.githubusercontent.com/assets/5832943/6504932/f00e2e42-c33c-11e4-9513-be99404f9c27.png)

If the first list scrolls infinitely we could not reach the second list. 

Would it be possible instead to have another filter? Open, Closed, Pending?

_For example:_

![screen shot 2015-03-05 at 1 43 23 pm](https://cloud.githubusercontent.com/assets/5832943/6504983/a1015dd2-c33d-11e4-89fd-c4fda9580fdf.png)

 I'm afraid if we create multiple lists it will also complicate #633. Where as it would be simple to provide a button with a 'popover' to provide additional filtering via search:

_For example:_

![screen shot 2015-03-05 at 1 44 59 pm](https://cloud.githubusercontent.com/assets/5832943/6505010/f26094fe-c33d-11e4-9d64-353f9a1c2fc2.png)

**Comment by fabianschwarzfritz** [comment]
If we decide for the search functionality in #801 I would rather add the possibility close to the search filter. 

We could either add a custom filter, for example ```type:pending``` as github has it. 

Or we could just add a filter like the _author_ filter. I think this way is more convenient than adding a _pending_ entry between _open_ and _close_ buttons, because the _pending_ pull request will always be a subset of the _open_ pull requests.

With both of these approaches we would still have the _pending_ pull requests per repo. If we want a general list of _pending_ pull requests, I don't think it's a good idea to mix that with the repository specific list of pull requests. We could put it in the notification area, as @dfarr suggested. I also like Githubs way of doing it with the little notification icon in the header bar. This way we could link to a new page with only the purpose of displaying cross-repo pull requests that are relevant for that user.

**Comment by dfarr** [comment]
Perhaps the most useful part of this feature request is **across all repos**. A "pending" tab does not address this. 

@rwreynard what is the most important aspect of this feature - the ability to see "pending PRs", or the ability to see a mish-mash of PRs across multiple repos?

**Comment by rwreynard** [comment]
@dfarr great question! Let me go back through the notes...

Okay, this came up with one very active developer on a team with tons of pull requests - lots going on. She would really welcome the ability (somehow) to be able to distinguish pull requests she cares most about - in her words "the pull requests I need to review". We tried the branch filter / highlight idea, but it isn't well understood in its current form. Is there some other way we could think of? I can also spend some time on this tomorrow. Her point was more to *only* see the open PRs that she needs to work on, until she chooses to view all open PRs. This general idea came up A LOT in the initial research where folks are accustomed to being assigned code to review - it's important for people to feel like they know what they in particular need to be reviewing.

A separate point was raised about surfacing open PRs, stars, & issues on the Repo list page (for teams that actively work in a lot of repos all the time).

No-one has raised the "across all repos" idea, possibly because we haven't heard from a team that is dealing with both lots of repos + lots of PRs! Project Norman would be a good team to get input from if we think this is the best way to go.

**Comment by dfarr** [comment]
Thanks Rachel. Given this insight, I like the "pending" tab idea.

Pending = "**open** PRs where I have not given a ninja star"

However this raises some pagination issues as pointed out before. I think we can work around this by treating pending PRs as open PRs.

**Comment by casche** [comment]
@dfarr Are you suggesting a Pending Tab at the same level as 'Pull Requests' and 'Team'. Or a Filter like Open/Closed (the screenshot above). ?

**Comment by dfarr** [comment]
As discussed lets close for now and revisit at a later date

**Comment by PeteFromNZ** [comment]
I would like to see all open PRs across all repros.  Our team works across multiple repros and making sure open PRs are getting dealt with for the entire product is critical.  Currently I think I need to go hunting in a lot of repros to see this.  I think microservices mean that a lot of teams are more likely to have this problem?

**Comment by Dhundia** [comment]
I would love to have this feature for the same reason @PeteFromNZ mentioned. We have tons of repos since we have fully event driven microservices architecture and PRs fall through the cracks sometimes sitting for review. Having a view for open PRs across repos which can then be filtered by the author or reviewer would be great!

**Comment by fabianschwarzfritz** [comment]
Hi @Dhundia ,

thanks for the reply! Unfortunately ReviewNinja is no longer maintained or developed, so I can help you here. I understand why this is a need feature and helpful for you. 

Maybe you can try to achieve the same with the [existing pull request overview](https://github.com/pulls) on github (enterprise). There's rich API GitHub which provides a way to add [custom filters](https://docs.github.com/en/github/administering-a-repository/finding-information-in-a-repository/using-search-to-filter-issues-and-pull-requests). Maybe with this it's possible for you to create such an overview 🙂 ?

Bests, Fabian
