### ISSUE TITLE
Scrollbar always on for search results?

### ISSUE THREAD

**Issue by casche** [reviewninja/review.ninja#710]
OS X Yosemite / Safari

IMO I got a little anxious when I searched 'reviewninja' to add a repository and I didn't see reviewninja/reviewninja. You do not see the scrollbar until you actually scroll.

I would prefer the scrollbar to show when you 'can' scroll (more results than space), or always. What do you think ?

**Comment by fabianschwarzfritz** [comment]
+1: I like the idea! I'd prefer to see the scrollbar only when where are actually more results to display. 

We should double check the current behavior and the one we might change to with other OS as well.

**Comment by dfarr** [comment]
OSX hides the scrollbar by default unless scrolling, we can force show with css but only in [some browsers](http://davidwalsh.name/osx-overflow)

**Comment by fabianschwarzfritz** [comment]
I implemented and now the scrollbar is always visible. However because the background of the scrollbar part is grey, the white and the green hover are not the background of the scrollbar. Take a look at the screenshot and you will realize what I mean. Do you like how it looks like?
![screen shot 2015-02-16 at 9 14 51 am](https://cloud.githubusercontent.com/assets/1759672/6216201/7b073464-b5bc-11e4-887b-ed5f5c8456c3.png)

**Comment by dfarr** [comment]
The styles are again only browser-specific (webkit browsers only). I would suggest letting the browsers/os handle whether or not the scrollbar shows by default.

**Comment by fabianschwarzfritz** [comment]
Yep, agreed, as this scrollbar does not look that good with they weird grey background, the solution I tried is not that good. :+1:
