### ISSUE TITLE
New commits in pull request hides issue highlights in diff

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#869]
We start with a pull request for changes in multiple files.
We create issues in said files in several places.
Requester fixes one of the issues and pushes a commit to pull request.

You can no longer see issue highlights (exclamations by the line numbers) in the diff, unless the issue is on the file that was changed in the last commit.

**Comment by dfarr** [comment]
Hi @disordered, can you describe what you would prefer/expect to happen in this scenario?

For the time being you may click on the '+' icon in the top right to manually expand the file.

**Comment by disordered** [comment]
I am not sure what you call the exclamation mark that marks the line numbers on the file where issue is attached. I'll refer to them as issue highlights.

Check this review: http://app.review.ninja/disordered/ReviewNinja-Welcome/pull/3

Note that review has 3 open issues (one for each file in the repository). Each issue has a reference to some line numbers. However, the exclamation marks (by the line numbers) are not visible, except for issue 4 (only when you open the issue details).
The pull request has received one commit after it was created.

Ideally, all highlights should remain visible even after new commits were done. I understand that sometimes the issue might no longer be valid (or at least the lines), in which case it should still show highlights for those files that were not touched since pull request was created.
Alternatively, or maybe in addition, it would be nice to be able to select diff between certain commits in pull request, in which case issue highlights could be visible there. Now you can only view the diff between base and latest commit.

Finally, if you click on any of the issues, it shows only the diff of the last commit on pull request. So if you open issue 5, for example, the diff view becomes completely useless.

**Comment by dfarr** [comment]
I misunderstood *when* the issue highlight is being hidden. Let me try to explain what is happening here, I would love to hear your feedback as this is an often misunderstood feature of ReviewNinja.

When we create an issue we use two pieces of information to generate a "unique key":
1) the sha of the head commit of the PR
2) the file path and line number of the line(s) you have selected. (optional)

Issues **must** be pinned to commits. Here is why: if I have one line of code, I could completely change it in a future commit. It would still be the same line number, but the intent and purpose could be completely different than the line someone created an issue on. This is why the line highlights do not show up - the comparison no longer includes the commit the issue was created on.

Now at any given point in time we are usually showing the diff between two commits, the base commit and the head commit (this is exactly how GitHub does it with PRs). However, **if** you are viewing an issue and **if** there have been new commits on the PR since the issue was created then we will show a comparison between the head commit of the PR and the commit where the issue was created.

If you notice at the top there is a little "git graph" that changes when this happens. You can actually click on those nodes to switch the current comparison. You can see an example [here](http://app.review.ninja/disordered/ReviewNinja-Welcome/pull/3/4).

The motivation for showing the "issue comparison" is to (hopefully) show a simple change that was implemented via a new commit, if the problem was fixed it should be obvious. I would love to hear your opinion on this, is this what you expected or is it something totally unexpected?

**Comment by disordered** [comment]
I think we are on the same page on how it currently works. However, I think it is not very useful and in some cases really gets in the way.

I don't have an opinion on how it should behave exactly, but here are some suggestions/thoughts:
* Showing latest commit diff on every issue really gets in the way, because said commit might not be related to issue being shown. I think at the very least, opening an issue with a link to the file should include the latest version of file being linked. That said, this could become very confusing if it would show latest revision + the file linked in the issue. Maybe, if latest revision does not include changes to the file, it should show the diff from the base instead.
* You mentioned that issue marks might have been invalidated by the commit, therefore you hide them. That is not really true, if you open issue 4 in the pull request that I linked above, you will see that issue mark is still present on the line that the latest commit have changed. So other marks are not visible because the latest commit did not include changes to those files.
* I think what is really missing is the ability to easily toggle between the diffs when the issue link was created and the current state of the commit. I would use this to both remind myself why the issue was created and whether it was addressed sufficiently. By the way, this is the same problem github has with comments in pull requests. Making a new commit, hides all comments (which is even worse).
* Maybe clicking the link in issue should switch to the diff when the issue was created. Clicking again switches to the latest revision.
* Issue marks in the diff could be retained as well if the line number exists (but maybe rendered in different color to signal that they were created on different revision). Clicking the exclamation mark, could switch the diff to the revision when issue was created...not sure how this would work with multiple issues on the same line.
* The revision graph could be broader. For example it could show all commits on pull request and mark those commits that have issues attached with an exclamation mark. It could allow showing diff not only between latest revision but any scope, i.e. between commits 3 and 7. For inspiration taken from gerrit:
![diff-selector](https://cloud.githubusercontent.com/assets/5319649/7369377/f921d584-edb1-11e4-8f07-20cad030c9a3.png)

* If review ninja implements feature to close pull request issues in commit messages, then you would know exactly when the issue was addressed. In which case it could allow to toggle between diffs when issue was created (to see what was the problem) and diff when issue was closed.


I hope this helps
