### ISSUE TITLE
A way to define more "roles" for code reviewers?

### ISSUE THREAD

**Issue by Thatkookooguy** [reviewninja/review.ninja#936]
If we have a Javascript expert and a CSS is it able to require 2 stars for a change, one for a review of a javascript expert and the other got a review is a CSS expert?

Maybe some ownership star for a reviewer that knows that particular file?

This can help getting the right reviewer to star a change and not just someone that don't understand that part of the project.

**Comment by Thatkookooguy** [comment]
This way review ninja can assign a random person on the team with the right privileges to review a change. An option to select a reviewer randomly or choose a specific one would be amazing :-)

**Comment by dfarr** [comment]
Added as a feature request :smile:

**Comment by dfarr** [comment]
We feel that enabling hard set roles and permissions for ReviewNinja code review goes against the philosophy of ReviewNinja. ReviewNinja is a lightweight code review tool where the validity of ninja star has more to do with the **merit** of the person who gave this ninja star. This is why we always display the image of the user who starred next to the star itself. In ReviewNinja this association of *people* with ninja stars is our preferred manner of defining rules for code review.

**Comment by Thatkookooguy** [comment]
what about someone who's new to a company and doesn't know the merit of the other people in the company? What I suggested gives a very simple solution to the office small talk "ask john to review this instead of me since I know nothing about X"

I don't understand how giving people a more defined role makes their merit less great. It improves it.

this suggestion doesn't change the fact that ReviewNinja (or any kind of code review) is about people and their approval (ninja stars)

But it's your decision eventually. If you guys don't want to implement this it's your decision :-)

**Comment by dfarr** [comment]
For the time being, we are not implementing this in order to focus on other requests. I also just wanted to express our philosophy and reasoning here. In the future, if we see this is heavily requested (or we get a pull request :stuck_out_tongue:) we will reconsider.

But, we do feel that this is a can of worms, unfortunately. We would need to know *who* owns *what* files (probably via a regex), this info would need to be actively maintained, and then we would need to dynamically calculate the review requirements based on what files make up the pull request. Having an informal, merit-based system takes longer to become familiar with, but we feel the ease-of-use is worth this trade-off.
