### ISSUE TITLE
Missing a "Preview" tab or button for comments editing

### ISSUE THREAD

**Issue by golubev** [reviewninja/review.ninja#966]
It would be great to add a "Preview" tab or button for comments editing. I often use this feature commenting on GitHub. Especially when using some markdown features (not only the plain text).

**Comment by dfarr** [comment]
Implemented! After typing a comment a "preview" button should appear in the upper right.

**Comment by golubev** [comment]
Thanks, @dfarr. That's nice.

What do you think about language-specific syntax highlighting, e.g. `’’’php`?
```php
$a = 1;
$b = 'f';
```

**Comment by dfarr** [comment]
GitHub uses [pygments](http://pygments.org/) to render to code syntax. Instead of defining pygment styles in css, they opt to do it with their own [style dsl](http://pygments.org/docs/styles/) into which third parties may plug in additional styles.

I have spent some time searching for a css clone of the styles/plugins used by GitHub with no luck so far. This is a feature I would like to have, I will keep a look out for a reasonable solution.

**Comment by golubev** [comment]
Thanks @dfarr! Wish you to have success with highlighting!
