### ISSUE TITLE
Show travis queued build in services

### ISSUE THREAD

**Issue by disordered** [reviewninja/review.ninja#988]
Right now Travis service shows up when the build starts. However, if travis has a queue and the commit is waiting to start build, review ninja will not show that Travis build is pending. If developers don't check service tab if Travis build has executed, it seems as everything passed successfully. This has lead on several occasions to code being merged before Travis verification has completed.

Would it be possible to include service as pending as soon as it is queued for the build? If not, maybe there are other options to address this, for example mark the project as always requiring Travis run? Or at the very least make service status more prominent - not requiring to switch to "Services" tab?

**Comment by dfarr** [comment]
All services integrate through GitHub and then out into other third party services, such as ReviewNinja. Because of this, there is no way for ReviewNinja to know that a travis build is queued until Travis writes a status to a commit. As soon as the happens RN will show the status.

One possible way to prevent merging before a build would be to take advantage of [required status checks](https://github.com/blog/2051-protected-branches-and-required-status-checks). This feature is now available on github.com, and was just released in the latest enterprise version.

**Comment by disordered** [comment]
Ah, perfect, this is exactly what we need.

**Comment by dfarr** [comment]
Awesome! I will go ahead and close this issue
